export const ACTION = {
  SIDE_MODAL_HEADER:"SIDE_MODAL_HEADER",
  SIDE_MODAL_FOOTER:"SIDE_MODAL_FOOTER",
  ALERT_SNACK_BAR: "ALERT_SNACK_BAR",
  IS_AUTHENTICATED:"IS_AUTHENTICATED",
  ADMIN_USER:"ADMIN_USER"
}
